name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Git. Clone
        run: |
          git clone https://github.com/TobiasMarschner/ferrishare.git
          cd ferrishare

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/file:latest .


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/file:latest